4 задачи по функциям и массивам
js-tasks-ru/jsbasic-20200727_olesya-mirzakhmedova pull request #6
Opened 2020-08-08 16:55 UTC by Lesyona

Стас, в 3 и 4 сильно говнокод?)

2020-08-08 17:02 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапозон
+ не должна менять исходный массив
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-08 19:01 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-09 10:24 UTC, dolgachio requested changes

2020-08-09 10:24 UTC, stas-dolgachov commented on 3-module/1-task/index.js
> +  return users.map((user) =>  user.name);
👍

2020-08-09 10:24 UTC, stas-dolgachov commented on 3-module/2-task/index.js
> +  return arr.filter((item) => item >= a && item <= b);
👍

2020-08-09 10:24 UTC, stas-dolgachov commented on 3-module/3-task/index.js
> +  return str
👍

2020-08-09 10:24 UTC, stas-dolgachov commented on 3-module/4-task/index.js
> +  users.map((user, index) => {
Здесь вы не совсем корректно использовали метод `map`, ведь вы игнорируете массив, который он возвращает. Если вы хотите решить эту задачу подобным образом, то заменит t метод `map` на `forEach`. 

Или используйте комбинацию методов `map` и `filter`.

2020-08-09 10:24 UTC, stas-dolgachov commented on 3-module/5-task/index.js
> +  let numArray = str
👍

2020-08-09 14:33 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-10 09:05 UTC, dolgachio approved these changes

2020-08-10 09:05 UTC, merged